my.lip <- read.table("lip_sasa.dat")
my.lip <- read.table("lip_sasa.tsv")
my.pkr <- read.table("PKref_sasa.tsv")
head(my.lip)
head(my.lip)
head(my.lip$V9)
mean(my.lip$V9)
mean(my.pkr$V9)
wilcox.test(my.lip$V9,my.pkr$V9)
d.lip<-density(my.lip$V9)
d.pkr<-density(my.pkr$V9)
pdf("density.pdf")
plot(d.pkr, main="SASA Density")
polygon(d.pkr, col="azure4",border="black")
plot(d.lip,add=T)
dev.off()
q()
pdf("density.pdf")
plot(d.pkr, main="SASA Density")
polygon(d.pkr, col="azure4",border="black")
lines(d.lip)
polygon(d.lip, col="darkolivegreen4",border="black")
dev.off()
q()
pdf("sasa_boxplot.pdf")
par(oma=c(1,1,1,1),mar=c(2,3,1,1),mgp=c(2,1,0), mfrow=c(2,2))
boxplot(my.lip$V9, my.pkr$V9, col=c("#7FBF26","gray40"), names=c("ntSP","PKref"), ylab="<SASA Per Residue>", outline=F)
dev.off()
q()
wilcox.test(my.lip$V9,my.pkr$V9)
q()
